app = "xforce-devthon-backend"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "node server.js"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]